In [12]:
import numpy as np
x1 = np.array([range(100), range(311,411), range(100)])
print(x1)
print(x1.shape)

[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
   36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
   54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
   72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
   90  91  92  93  94  95  96  97  98  99]
 [311 312 313 314 315 316 317 318 319 320 321 322 323 324 325 326 327 328
  329 330 331 332 333 334 335 336 337 338 339 340 341 342 343 344 345 346
  347 348 349 350 351 352 353 354 355 356 357 358 359 360 361 362 363 364
  365 366 367 368 369 370 371 372 373 374 375 376 377 378 379 380 381 382
  383 384 385 386 387 388 389 390 391 392 393 394 395 396 397 398 399 400
  401 402 403 404 405 406 407 408 409 410]
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
   36  37  38  39  40  41 

In [5]:
x2 = np.array([range(100,200), range(311,411), range(100,200)])
print(x2)

[[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
  118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
  136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
  154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
  172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
  190 191 192 193 194 195 196 197 198 199]
 [311 312 313 314 315 316 317 318 319 320 321 322 323 324 325 326 327 328
  329 330 331 332 333 334 335 336 337 338 339 340 341 342 343 344 345 346
  347 348 349 350 351 352 353 354 355 356 357 358 359 360 361 362 363 364
  365 366 367 368 369 370 371 372 373 374 375 376 377 378 379 380 381 382
  383 384 385 386 387 388 389 390 391 392 393 394 395 396 397 398 399 400
  401 402 403 404 405 406 407 408 409 410]
 [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
  118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
  136 137 138 139 140 141 

In [6]:
y1 = np.array([range(501,601), range(711,811), range(100)])
print(y1)

[[501 502 503 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518
  519 520 521 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536
  537 538 539 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554
  555 556 557 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572
  573 574 575 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590
  591 592 593 594 595 596 597 598 599 600]
 [711 712 713 714 715 716 717 718 719 720 721 722 723 724 725 726 727 728
  729 730 731 732 733 734 735 736 737 738 739 740 741 742 743 744 745 746
  747 748 749 750 751 752 753 754 755 756 757 758 759 760 761 762 763 764
  765 766 767 768 769 770 771 772 773 774 775 776 777 778 779 780 781 782
  783 784 785 786 787 788 789 790 791 792 793 794 795 796 797 798 799 800
  801 802 803 804 805 806 807 808 809 810]
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
   36  37  38  39  40  41 

In [7]:
y2 = np.array([range(501,601), range(711,811), range(100)])
y3 = np.array([range(401,501), range(211,311), range(100)])

In [8]:
x1 = np.transpose(x1)
print(x1)

[[  0 311   0]
 [  1 312   1]
 [  2 313   2]
 [  3 314   3]
 [  4 315   4]
 [  5 316   5]
 [  6 317   6]
 [  7 318   7]
 [  8 319   8]
 [  9 320   9]
 [ 10 321  10]
 [ 11 322  11]
 [ 12 323  12]
 [ 13 324  13]
 [ 14 325  14]
 [ 15 326  15]
 [ 16 327  16]
 [ 17 328  17]
 [ 18 329  18]
 [ 19 330  19]
 [ 20 331  20]
 [ 21 332  21]
 [ 22 333  22]
 [ 23 334  23]
 [ 24 335  24]
 [ 25 336  25]
 [ 26 337  26]
 [ 27 338  27]
 [ 28 339  28]
 [ 29 340  29]
 [ 30 341  30]
 [ 31 342  31]
 [ 32 343  32]
 [ 33 344  33]
 [ 34 345  34]
 [ 35 346  35]
 [ 36 347  36]
 [ 37 348  37]
 [ 38 349  38]
 [ 39 350  39]
 [ 40 351  40]
 [ 41 352  41]
 [ 42 353  42]
 [ 43 354  43]
 [ 44 355  44]
 [ 45 356  45]
 [ 46 357  46]
 [ 47 358  47]
 [ 48 359  48]
 [ 49 360  49]
 [ 50 361  50]
 [ 51 362  51]
 [ 52 363  52]
 [ 53 364  53]
 [ 54 365  54]
 [ 55 366  55]
 [ 56 367  56]
 [ 57 368  57]
 [ 58 369  58]
 [ 59 370  59]
 [ 60 371  60]
 [ 61 372  61]
 [ 62 373  62]
 [ 63 374  63]
 [ 64 375  64]
 [ 65 376  65]
 [ 66 377 

In [9]:
x2 = np.transpose(x2)
y1 = np.transpose(y1)
y2 = np.transpose(y2)
y3 = np.transpose(y3)

In [10]:
x_train = np.random.random((1000, 20))
print(x_train)

[[0.72606722 0.84752732 0.90167    ... 0.71958585 0.76757911 0.21018657]
 [0.72915605 0.11171743 0.78387892 ... 0.76244353 0.63380529 0.8320127 ]
 [0.53290169 0.34377577 0.74196082 ... 0.16492112 0.89704892 0.38741335]
 ...
 [0.87493125 0.64620248 0.50603177 ... 0.30583091 0.77721488 0.08658885]
 [0.17451785 0.38474984 0.71766603 ... 0.64690457 0.18700631 0.83272942]
 [0.48976374 0.9014361  0.28527524 ... 0.7114654  0.2099263  0.3911091 ]]


In [11]:
print(x_train.shape)

(1000, 20)


In [17]:
x_train = np.random.random((10, 20))
print(x_train)

[[7.72378072e-01 3.83634566e-01 7.02984313e-01 5.47204709e-01
  8.12090580e-02 3.50434752e-01 8.20521389e-01 6.24082572e-01
  5.36214803e-01 1.23065207e-01 7.60373652e-01 1.45156921e-01
  2.31914712e-01 6.17100555e-01 1.81618781e-01 3.37231419e-01
  6.02147684e-01 6.25376969e-01 2.86445370e-01 4.65004863e-01]
 [5.32866401e-01 8.18514950e-01 3.93329358e-01 5.14763244e-01
  7.96568419e-01 9.83433108e-01 4.89567553e-01 5.95685241e-01
  1.68153386e-01 2.13979547e-01 9.34824571e-01 4.78649846e-01
  9.17959026e-01 5.11947030e-01 3.24032983e-01 6.26500769e-01
  2.19424364e-01 2.21692769e-01 4.99219950e-01 9.08889463e-01]
 [7.83723827e-01 9.64819229e-03 5.74669713e-01 8.35717112e-01
  6.48084341e-01 2.50989103e-01 8.44364190e-01 5.16736608e-01
  2.89841758e-01 2.07176956e-01 7.85818223e-01 5.87687356e-02
  1.87044040e-01 9.50591935e-02 9.66758509e-01 3.43857207e-01
  5.59181889e-01 2.76063720e-01 4.42772048e-01 4.63552448e-01]
 [5.56961929e-01 7.23043312e-01 7.61838068e-01 3.32093478e-02
  9.2

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import SGD
import keras.utils

# Generate dummy data
import numpy as np
x_train = np.random.random((1000, 20, 2))
y_train = keras.utils.to_categorical(np.random.randint(10, size=(1000, 1)), num_classes=10)
x_test = np.random.random((100, 20, 2))
y_test = keras.utils.to_categorical(np.random.randint(10, size=(100, 1)), num_classes=10)

model = Sequential()
# Dense(64) is a fully-connected layer with 64 hidden units.
# in the first layer, you must specify the expected input data shape:
# here, 20-dimensional vectors.
model.add(Dense(64, activation='relu', input_dim=20))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy',
              optimizer=sgd,
              metrics=['accuracy'])

model.fit(x_train, y_train,
          epochs=20,
          batch_size=128)
score = model.evaluate(x_test, y_test, batch_size=128)